### ISSUE TITLE
BT connect / authentication failed

### ISSUE THREAD

**Issue by s--p** [d03n3rfr1tz3/esp32-divoom#6]
Hi there,

just received a Timebox Evo for Christmas and found your integration for Home Assistant and also this esp32 bluetooth proxy (thanks a lot for your effort!). I followed your instructions, changed all my credentials etc. flashed it (tried on a ESP32DEVKITV1 and D1 Mini) but when I try the connect step I only get the following error (with both of them):

```
CONNECT XX:XX:XX:XX:XX:XX 2
[ 35756][E][BluetoothSerial.cpp:996] connect(): connect failed
[ 37002][E][BluetoothSerial.cpp:528] esp_bt_gap_cb(): authentication failed, status:9
```

I redacted the MAC Address, but I see in the VSCode Monitor that it retries again and again, and everytime the Bluetooth Icon on the Timebox appears for a second and then changes back to the Clock, so I assume the MAC Address is correct. I also tried several ports up to 10 but it also doesn't work. BT on my phone is turned off so it's definitely not connected to anything else. How can I fix this? Any suggestions?

Thanks in advance and Merry Christmas!

**Comment by d03n3rfr1tz3** [comment]
Hey, Merry Christmas!

Did you also try port 1? Just want to make sure, because your example shows port 2 and you mentioned going up to port 10. The Timebox Evo typically used port 1 for the serial communication AFAIK.

Guessing by the actual error you got, it is very likely a pairing problem. Typically pairing "just works" on those devices. But on my Ditoo I saw a password-feature. Maybe the Timebox also supported that and you did set a password with your phone? Because the library currently does not support sending a password.
Can you remember, how you paired your Timebox to your phone (via bluetooth?). Was there some sort of number you needed to type into your phone? I just hope they did not change/upgrade the pairing process, because that would make things more complicated.

**Comment by s--p** [comment]
Hey, 
thanks for the quick reply! I also tried starting with Port 1, that was just a snippet from the console I copied from the whole process of going upward.
Yeah I think I had to enter 0000, I set it up with the app first before I got back to my apartment where I tried further steps to integrate it with Home Assistant. I also tried resetting it with holding the "+" and "-" buttons pressed for like 20 seconds, but don't know if it actually worked because it stilled showed the weather and temperature. For a real hard reset I would imagine everything should have gone back to factory defaults. The manual also doesn't say anything about hard reset, that's something I found on Reddit. There is this hole under the power button, and another one next to the USB-C charging port, I assume at least one of them is for the Microphone and the other one might be to reset it? But I also don't want to just poke in there and damage something accidentally.
Weird thing though is that my Laptop can just pair with it, without having to enter any code.

**Comment by s--p** [comment]
Ok, I figured it out, the Android App is horrible so I couldn't find the menu from the original pairing, but I unpaired it again and tried to go through the steps again and I found it again, there's a switch in the app when you set up a new device that says "Connect with password" and if you deactivate that then it's connecting with the ESP32 as well!

**Comment by s--p** [comment]
So this can be closed, but maybe as a reminder for everyone in the future you can put it in the readme as well that you shouldn't set a Pin to connect with when setting up the device with the app ;)

Thanks again!

**Comment by d03n3rfr1tz3** [comment]
Nice, good that you found that password menu in the app before poking something into an unknown hole 😏

I will probably add the possibility for passing through the pin/password somehow (through serial commands and such). That is surprisingly easy on the ESP32, but hard in python for my Home Assistant integration (because you can't really control the pairing part from the python socket code). That's why it's currently not supported, as it might confuse people using the HA integration, when combined with this ESP32 library, which basic idea was just being a proxy.
